### ISSUE TITLE
Support remaining GEDI collections

### ISSUE THREAD

**Issue by chuckwondo** [MAAP-Project/gedi-subsetter#19]
We currently support the following GEDI collections:

- L2A (10.5067/GEDI/GEDI02_A.002)
- L4A (10.3334/ORNLDAAC/2056)

Add support for the remaining GEDI collections:

- L1B (10.5067/GEDI/GEDI01_B.002)
- L2B (10.5067/GEDI/GEDI02_B.002\r\n): **NOTE:**, the actual DOI value ends with the literal characters `\r\n`, which is not a valid DOI. See the [CMR entry](https://cmr.earthdata.nasa.gov/search/collections.umm_json?doi=10.5067%2FGEDI%2FGEDI02_B.002%0D%0A) as well as the [DOI link](https://www.doi.org/10.5067/GEDI/GEDI02_B.002), which redirects to the collection's info page.
- ~~L3 (10.3334/ORNLDAAC/1952)~~
- ~~L4A-GW (10.3334/ORNLDAAC/2028): [L4A Golden Weeks](https://cmr.earthdata.nasa.gov/search/collections.umm_json?doi=10.3334/ORNLDAAC/2028) (@wildintellect, do we want users to be able to specify this one?)~~
- ~~L4B (10.3334/ORNLDAAC/2017)~~

See the [full list of GEDI collections in the CMR](https://cmr.earthdata.nasa.gov/search/collections.umm_json?short_name=GEDI*&options%5Bshort_name%5D%5Bpattern%5D=true).

## Acceptance Criteria

- [x] Accept any of the additional "logical" names listed above as values for the `doi` input
- [x] Enhance validation of `doi` value by requiring the following to be true about the retrieved collection metadata (throwing a "ValueError" error otherwise):
   - [x] The ShortName property contains (starts with?) "GEDI"
   - [x] Either the DataFormat property or the value of the "Data Format" additional attribute is "HDF5"
```

**Comment by wildintellect** [comment]
* Remove L3 and L4B those are GeoTiff and COGs - not point data. Their subsetting is done via `rio tiler` and `rasterio` on the fly.
* L4A-GW - ask the UWG but probably not since it's Version 1, also this data is in the full set it's just a temporal filter.

This ticket is also a little misleading. Simply enabling the correct DOI doesn't mean a particular collection will work. So I would make a ticket for each collection that needs to be supported, and a task in each is to modify the collection/doi handler to enable it.

**Comment by chuckwondo** [comment]
Actually, simply enabling the correct DOI, _does_ mean the particular collection will work. There is no logic within the algorithm that is collection-specific (other than being scoped only to GEDI collections).

Therefore, the effort to support the remaining GEDI collections is nothing more than adding the mappings from logical names to DOIs, as listed above (along with a bit more logic to make sure that if a user specifies a DOI, rather than a logical name, the DOI is for a GEDI collection, not for some arbitrary collection).

I have removed L3, L4B, and L4A-GW from the list above.
