### ISSUE TITLE
Date filtering

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/gedi-subsetter#38]
We completely missed allowing users to pass in a Data Range to be used by CMR queries. I'm identifying this as a bug because it can lead to excessive granule downloading when the full Date Range of all GEDI data is used.

## Solution
- [ ] Add argument to algorithm that takes date ranges in the same manner as CMR
- [ ] Pass the values to the internal CMR query.

**Comment by wildintellect** [comment]
https://github.com/MAAP-Project/gedi-subsetter/blob/bdf641e502a79d0d388b02ed5b3f4b34d7fef836/src/gedi_subset/subset.py#L343-L347 is where we do the Granule search, and should add the date filtering.

**Comment by chuckwondo** [comment]
I'm working on this. I should be able to submit a PR on Monday.

**Comment by chuckwondo** [comment]
I'm going to submit a PR, which I believe to be ready to go, but I'm still waiting on Brian at JPL to address an issue I am encountering while attempting to do some testing from the command line in the new ADE at ade.maap-project.org, rather than the old ade.ops.maap-project.org.

**Comment by chuckwondo** [comment]
https://github.com/MAAP-Project/gedi-subsetter/pull/39

**Comment by freitagb** [comment]
Blocked by access denied on the GEDI_L2B due to issue in maap_py

**Comment by chuckwondo** [comment]
Fixed in v0.6.0, #39
