### ISSUE TITLE
TypeError: list indices must be integers or slices, not str (multiple GPolygons in granule metadata)

### ISSUE THREAD

**Issue by chuckwondo** [MAAP-Project/gedi-subsetter#42]
Some users encounter the following error after a job has been running without issue for a period of time:

```
TypeError: list indices must be integers or slices, not str
```

Here is an command that eventually ran into this error:

```
conda run /app/gedi-subsetter/src/gedi_subset/subset.py --verbose --aoi /projects/shared-buckets/nehajo88/Data/NFI_data/Mexico/StratoForm_CONIFERAS.gpkg --doi L4A --lat lat_lowestmode --lon lon_lowestmode --beams all --columns "agbd, agbd_se" --query "l4_quality_flag == 1 and sensitivity > 0.95" --limit 10000
```

**Comment by chuckwondo** [comment]
Using this variation of the command above within the ADE, I was able to reproduce the error:

```
./subset.sh --aoi /projects/shared-buckets/nehajo88/Data/NFI_data/Mexico/StratoForm_CONIFERAS.gpkg --doi L4A --lat lat_lowestmode --lon lon_lowestmode --columns "agbd, agbd_se" --query "l4_quality_flag == 1 and sensitivity > 0.95"
```

The cause of the error is granule metadata where the value at the path `Spatial.HorizontalSpatialDomain.Geometry.GPolygon` within the metadata is a `list`, not a `dict`, but our `granule_intersects` function assumes it is always a `dict` (i.e., a single value, not multiple values).

Due to a quirk in parsing XML to a `dict`, when an element can contain only a single child element, the parent is translated into a single object rather than a list containing a single object. Therefore, the logic to support both a single element and multiple elements cannot be the same.

Given that we assumed `GPolygon` would only ever be a single item, we did not account for the rare case where it is a list of items. Therefore, we must add logic to recognize and handle both cases.

Here is an example of where `GPolygon` is a list of 2 `Boundary` items: https://cmr.earthdata.nasa.gov/search/granules.echo10?concept_id=G2613721393-ORNL_CLOUD

In most cases, `GPolygon` is an object, not a list, and it contains a single `Boundary` item, and this is the situation that we have coded for, not considering the case of a list, as shown at the link above.

Here is our Slack conversation about this issue: https://esa-nasa-maap.slack.com/archives/C01308ZHELF/p1685131816528539?thread_ts=1681321078.902189&cid=C01308ZHELF

cc: @wildintellect

**Comment by chuckwondo** [comment]
Fixed in v0.6.0, #39

**Comment by chuckwondo** [comment]
> @chuckwondo did we decide if we need to contact the DAAC about bad metadata records with extra polygons?

I don't think we made a decision on this. Since v0.6.0 of the algorithm now handles multiple polygons, it's no longer a problem for the algorithm itself. So the decision is now simply a matter of determining if the metadata we encountered with multiple polygons represents erroneous metadata. Given what you were able to visualize, perhaps it is, but I'll leave the decision to you since this is your area of expertise.

**Comment by wildintellect** [comment]
It's a bug in the DAAC metadata - we should reach out. Will open a ticket elsewhere about this. cc: @freitagb

**Comment by freitagb** [comment]
To be clear, it's [this granule](https://search.earthdata.nasa.gov/search/granules?p=C2237824918-ORNL_CLOUD&pg[0][v]=f&pg[0][id]=GEDI_L4A_AGB_Density_V2_1.GEDI04_A_2022048192536_O18035_03_T06279_02_003_02_V002.h5&pg[0][gsk]=-start_date&g=G2613721393-ORNL_CLOUD&q=GEDI_L4A_AGB_Density_V2_1_2056&tl=1687357473.771!3!!&lat=7.522396774508195&long=-98.578125) right? I see the multiple polygons in the metadata, but i only think they show one on the Earthdata Search map (at least i don't see any breaks in the swath outlined). Do you have a visual of the two polygons somewhere?

**Comment by freitagb** [comment]
As a note for development though, we do have valid cases for multiple boundaries in HLS when we have a tile that intersects the dateline (see [this granule](https://search.earthdata.nasa.gov/search/granules/granule-details?p=C2021957295-LPCLOUD&pg[0][v]=f&pg[0][gsk]=-start_date&g=G2715180545-LPCLOUD&q=hls&sb[0]=177.04688%2C-18.56544%2C-179.92969%2C-15.92909&tl=1687357987.155!3!!&lat=-15.890625&zoom=1)). Just something to be aware of for the future.

**Comment by wildintellect** [comment]
This isn't an Anti-meridian issue, 
![image](https://github.com/MAAP-Project/gedi-subsetter/assets/306179/078befa4-84c7-4387-9759-d6f2d12d1258)

What we still need to do is extract the points from the granule and overlay to see which of these polygons is the correct one.

**Comment by wildintellect** [comment]
@chuckwondo correct, that's why I want to identify which one is invalid and have @freitagb report that to the DAAC.

**Comment by freitagb** [comment]
Right, i saw that it wasn't an antimeridian issue. Just mostly a note that we'll have valid data with multiple boundaries. Given that the code can properly handle multiple boundaries we should be okay. Perhaps the polygon displayed in Earthdata Search is simply too zoomed out to see the overlapping polygons.
