### ISSUE TITLE
Directly read granule files from S3 rather than downloading them

### ISSUE THREAD

**Issue by emileten** [MAAP-Project/gedi-subsetter#54]
Came up after a conversation with @wildintellect 

Currently, each data file gets fully downloaded to disk with an HTTP request (using earthdata login?), and then processed.

We have access to the S3 bucket where the data is stored, so we should experiment with directly reading it from that location, using `fsspec`.

**Comment by wildintellect** [comment]
@emileten I'd forgotten, we implemented S3 with temporary credentials, but it does download https://github.com/MAAP-Project/gedi-subsetter/blob/58c87ab907bc3b121510eeabdeb2b8e63c7df999/src/gedi_subset/maapx.py#L79 and it would be interesting to try direct read of files, also noting that we have an Role we can use to bypass the credential portion.

**Comment by chuckwondo** [comment]
For direct reads we should be able to [assume the appropriate role](https://github.com/NASA-IMPACT/active-maap-sprint/issues/884#issuecomment-2004077098).
