### ISSUE TITLE
Allow user to specify which BEAMs to subset

### ISSUE THREAD

**Issue by chuckwondo** [MAAP-Project/gedi-subsetter#6]
Currently, we subset _all_ BEAMs within a granule file (`.h5`), but a user should be able to limit which ones to subset, in any of the following ways:

1. All beams: `"all"`
2. Named beams: comma-separated list of beam names, with or without the `"BEAM"` prefix(es). Examples:
   - `"BEAM0101,BEAM0110,BEAM1000,BEAM1011"`
   - `"0101,0110,1000,1011"`
   - `"0101,BEAM0110,1000,1011"`
3. Beam type: either `"coverage"` (implying BEAM0000, BEAM0001, BEAM0010, and BEAM0011) or `"power"` (implying BEAM0101, BEAM0110, BEAM1000, and BEAM1011)

## Acceptance Criteria

- [x] add a "beams" input to the algorithm that accepts the following values, and update the `subset_hdf5` function to select only the appropriate beams from the granule files:
  - exactly 1 of `all`, `coverage`, or `power`
  - OR, a comma-separated list of values from the following set (with or without the `BEAM` prefix): BEAM0000, BEAM0001, BEAM0010, BEAM0011, BEAM0101, BEAM0110, BEAM1000, BEAM1011

**Comment by jjfrench** [comment]
Tested 0.4.0 with suggested L4A and L2B inputs, both jobs succeeded.
