### ISSUE TITLE
Optimize s3fs read cache settings

### ISSUE THREAD

**Issue by chuckwondo** [MAAP-Project/gedi-subsetter#77]
Now that we are reading directly from S3 rather than downloading files, we must analyze the performance of the various cache type and block size settings exposed by the `s3fs.S3FileSystem.open` method. In particular, we want to tune the following options:

- `block_size` (bytes): default is 5MiB (5 * 1024 * 1024 == 5 * 2**20)
- `cache_type`: default is `"readahead"`; options are (description pulled from docs):
   - `all`: Cache entire contents of the file.
   - `background`: Cache holding memory as a set of blocks with pre-loading of the next block in the background. Requests are only ever made ``blocksize`` at a time, and are stored in an LRU cache. The least recently accessed block is discarded when more than ``maxblocks`` [default: 32] are stored. If the next block is not in cache, it is loaded in a separate thread in non-blocking way.
   - `blockcache`: Cache holding memory as a set of blocks. Requests are only ever made `blocksize` at a time, and are stored in an LRU cache. The least recently accessed block is discarded when more than `maxblocks` [default: 32] are stored.
   - `bytes`: Cache which holds data in a in-memory bytes object. Implements read-ahead by the block size, for semi-random reads progressing through the file.
   - `first`: Caches the first block of a file only. This may be useful for file types where the metadata is stored in the header, but is randomly accessed.
   - `mmap`: Memory-mapped sparse file cache.  Opens temporary file, which is filled blocks-wise when data is requested. Ensure there is enough disc space in the temporary location.
   - `parts`: Cache holding known file parts. [Note: it appears that this cache type requires _a priori_ knowledge of "parts" of the file, and will issue the following warning when no parts information is supplied in advance: "Read is outside the known file parts. IO/caching performance may be poor!"]
   - `readahead`: Cache which reads only when we get beyond a block of data. This is a much simpler version of BytesCache, and does not attempt to fill holes in the cache or keep fragments alive. It is best suited to many small reads in a sequential order (e.g., reading lines from a file).
- `fill_cache` (boolean): default is `True`. Per documentation: If seeking to new a part of the file beyond the current buffer, with this True, the buffer will be filled between the sections to best support random access. When reading only a few specific chunks out of a file, performance may be better if False.

We should run an experiment to determine which combination of `block_size` (1, 2, 4, 5, or 8 MiB), `cache_type`, and `fill_cache` provides the best performance and either hardcode those settings, or at least set them as the defaults.

**Comment by chuckwondo** [comment]
@wildintellect and I discussed possible approaches for this, and we agreed to do the following to get some initial information that will hopefully guide further experiments:

- Use 1 CPU to initially avoid using multiple processes that might introduce additional factors
- Subset only 100 granules
- Vary only `cache_type` (leaving `block_size` and `fill_cache` at their default values)

Specifically, we'll use the following inputs for each cache type identified above:

```python
inputs = dict(
    aoi=f"https://maap-ops-workspace.s3.amazonaws.com/shared/dschuck/iso3/GAB-ADM0.geojson",
    doi="L4A",
    lat="lat_lowestmode",
    lon="lon_lowestmode",
    columns="agbd, agbd_se, sensitivity, geolocation/sensitivity_a2, elev_lowestmode",
    query="l2_quality_flag == 1 and l4_quality_flag == 1 and sensitivity > 0.95 and `geolocation/sensitivity_a2` > 0.95",
    scalene_args="--html --reduced-profile",
    limit=100,
    cpus=1,
    s3fs_open_kwargs=json.dumps(dict(cache_type=cache_type)),
    queue="maap-dps-worker-8gb",
)
```

Further, we'll run only 1 job per cache type to hopefully identify which cache types are clearly better for our use case than others. Once we produce a smaller set of cache types worthy of additional experimentation, we'll run each combination of `cache_type` (excluding those identified as very obviously poor choices based on this initial experiment), `fill_cache`, and `block_size` some number of times (TBD) each to obtain statistics for comparison.

**Comment by chuckwondo** [comment]
Here are the initial elapsed time and peak memory metrics gathered (via Scalene) from 1 run per cache type (ordered fastest to slowest):

|`cache_type`|Elapsed (min:sec)|Peak memory (mb)|
|:----|-----:|-----:|
|background|6:10|101|
|all|6:18|131|
|blockcache|7:36|161|
|mmap|13:37|128|
|readahead|23:28|102|
|bytes|26:22|93|
|first|36:44|128|
|parts|37:36|123|

@wildintellect, where do you propose we go from here? It appears that perhaps only `all`, `background`, and `blockcache` are worth running further experiments with. I might also drop `blockcache` from consideration, given the high peak memory figure, but this _might_ be a fluke since it was only 1 run.

Further, I don't currently know how file sizes differ between the 4 GEDI collections we currently support, so I don't know if we should run a similar experiment for the other collections as well, as significantly different file sizes _might_ change the ranking of the cache types.

**Comment by wildintellect** [comment]
@chuckwondo I suppose you could run the same test with L2A. That is a good point that knowing the granule file size distribution for each product would be good background info. I wonder if the DAACs have that or if it can be queried/sampled from CMR?

I think it's fine to keep the top 3 and move on to the next test, tempting to even keep `mmap` out of interest or for comparison.

So I suppose now we need to decide on the sample size needed to find a statistical difference and rerun some iterations?

@abarciauskas-bgse @kylebarron

**Comment by kylebarron** [comment]
I'm not an expert on these caching strategies, but I'd guess that @vincentsarago has some experience

**Comment by vincentsarago** [comment]
I've never been able to use cache with fsspec 😓

**Comment by chuckwondo** [comment]
> I'm not an expert on these caching strategies, but I'd guess that @vincentsarago has some experience

We're not looking for help with the caching strategies. The table above shows a hint as to how each available caching strategy performs. We're looking for guidance on how many runs per caching strategy we should make in order to be able to draw statistically valid conclusions as to which strategy performs best (either in terms of time or memory).

For example, would it be sufficient to run each caching strategy 30 times (with all other inputs kept the same) in order to draw a conclusion as to which one allows the algorithm to run the fastest, or about which one consumes the least memory during our algorithm execution?

> @chuckwondo I suppose you could run the same test with L2A. That is a good point that knowing the granule file size distribution for each product would be good background info. I wonder if the DAACs have that or if it can be queried/sampled from CMR?

I can do some investigation here.

> I think it's fine to keep the top 3 and move on to the next test, tempting to even keep `mmap` out of interest or for comparison.

I think we should pull `mmap` into the mix as well. I reran each strategy again (except for `parts`) because I wanted to produce a different Scalene profile format than I did the first time around. All but `mmap` produced elapsed time and memory figures fairly similar to the first run, whereas `mmap` performed much more closely with the top 3, so I think it's worth including it in the next round.

The other question (in addition to "how many times do we run each strategy?") is which statistic do we use for comparison? Some reading I've been doing leads me to suggest that we use minimum (both for execution time and peak memory). One such interesting read is [Robust benchmarking in noisy environments](https://arxiv.org/pdf/1608.04295), which concludes:

> Our results suggest that using the minimum estimator
for the true run time of a benchmark, rather than the mean or
median, is robust to nonideal statistics and also provides the
smallest error. Our model also revealed some behaviors that
challenge conventional wisdom: simply running a benchmark
for longer, or repeating its execution many times, can render
the effects of external variation negligible, even as the error
due to timer inaccuracy is amortized.

The paper also provides an algorithm for estimating _n_, "the optimal number of benchmark repetitions required to minimize timer error and maximize the number of data points obtainable within a time budget." However, I don't think we have the time to make use of the algorithm, so we may need to refer to other sources for determining a "reasonable" _n_ to use.

**Comment by chuckwondo** [comment]
I suggest starting with 20 runs per combination and subset the entirety of Gabon (i.e., the same inputs given above, but with `limit` set large enough to get all intersecting granules, which I believe is roughly 1200, so setting limit to 2000 should suffice) so that we are running a realistic scenario (i.e. a scenario very much like users would run).

I believe this should give us a reasonable combination of repetitions with longer runtimes in order to produce meaningful results. We can choose a winner based upon what appears to be a good balance between runtime and memory. Ideally, the combination that produces the minimum runtime will also use the least amount of memory (or at least low enough memory not to require a different machine size).

If we want to produce a statistic that's a bit more interesting, we can compute 95% confidence intervals for the elapsed time and peak memory usage of each combination.

This would give us a total of 4 cache types (background, all, blockcache, and mmap) times 5 block sizes (1, 2, 4, 5, 8 MiB) times 2 fill caches (True, False) = 40 combinations, each repeated 20 times. (We might want to reduce this to 32 combos by eliminating the 1MiB block size).

In addition to agreeing on the number of repetitions per combo, we need to select a machine size. Of course, since the algorithm makes use of all available CPUs, the more CPUs the better, assuming that I/O capabilities are scaled with the CPU count.

Lastly, we'll want to also run our "baseline" version of the code that downloads files instead of directly reading S3 so we can see if any of the combos above actually perform any better than downloading.

**Comment by chuckwondo** [comment]
Here's the code I used to submit job combos:

```python
import json
from maap.maap import MAAP

maap = MAAP(maap_host="api.maap-project.org")
username = maap.profile.account_info()["username"]

queue="maap-dps-worker-32vcpu-64gb"

common_inputs = dict(
    queue=queue,
    algo_id="gedi-subset",
    username=username,
    aoi="https://maap-ops-workspace.s3.amazonaws.com/shared/dschuck/iso3/GAB-ADM0.geojson",
    doi="L4A",
    lat="lat_lowestmode",
    lon="lon_lowestmode",
    columns="agbd, agbd_se, sensitivity, geolocation/sensitivity_a2, elev_lowestmode",
    query="l2_quality_flag == 1 and l4_quality_flag == 1 and sensitivity > 0.95 and `geolocation/sensitivity_a2` > 0.95",
    scalene_args="--json --reduced-profile",
    limit=5000,
)

s3fs_inputss = tuple(
    dict(
        identifier=f"{cache_type}_{block_size_mb}MiB_{'fill' if fill_cache else 'nofill'}_{queue}",
        s3fs_open_kwargs=json.dumps(
            dict(
                cache_type=cache_type,
                block_size=block_size_mb * 1024 * 1024,
                fill_cache=fill_cache
            )
        ),
    )
    # Other cache types available, but excluded based on initial testing that
    # showed poor performance: "bytes", "first", "parts", "readahead" (default)
    for cache_type in ("all", "background", "blockcache", "mmap")
    for block_size_mb in (1, 2, 4, 5, 8)  # default: 5
    for fill_cache in (True, False)  # default: True
)

for _ in range(10):
    for s3fs_inputs in s3fs_inputss:
        maap.submitJob(version="s3fs-tuning", **common_inputs, **s3fs_inputs)

for _ in range(10):
    # Baseline: 0.7.1 is latest version using downloading
    # When identifier (tag) is not supplied, it defaults to "maap-api-submit".
    maap.submitJob(version="0.7.1", **common_inputs)
```

@wildintellect, after helping with the DPS job metrics gathering, I realized the job metrics are also super helpful for analyzing the s3fs cache tuning. I've attached metrics for the jobs I ran last week and earlier this week: [s3fs-caching-metrics.csv](https://github.com/user-attachments/files/15823348/s3fs-caching-metrics.csv). What the metrics don't include, however, are memory consumption figures, which I'll have to gather from the Scalene profiles.

There are around 10 jobs per combo (some failed, and some are from my first batch where I ran 1 job per combo as an initial test before kicking off more). Although we decided not to include cache type "first" (per previous comments), I included it because of this recent Pangeo discussion: https://discourse.pangeo.io/t/pangeo-showcase-hdf5-at-the-speed-of-zarr/4084/3

To gather more data, I've kicked off another 10 jobs per combo, but I excluded the cache type "first", because it performed quite poorly, contrary to the recommendation given by Martin Durant in the Pangeo discussion linked above.

So far, the results are pretty interesting, showing that downloading files (tag="maap-api-submit") lands roughly in the middle in terms of performance, so there are indeed cache/blocksize settings that can perform better than downloading.

The attached CSV file is sorted in ascending order of "min", where the stats are for the execution times in seconds. The "tag" column is in the format `CACHETYPE_BLOCKSIZE_[no]fill_QUEUE`, other than the download version, which has tag "maap-api-submit" (I forgot to give those jobs specific tags/identifiers, so that's the default).

Once the current batch of jobs complete, I'll gather stats again (across all batches) to see if there's any difference in ranking.

**Comment by chuckwondo** [comment]
I've completed ~30 runs for each combo, including the "download" (original) code and found that the `"first"` cache type ran significantly worse than everything else, including downloading. Of the remaining combinations, they all ran only _marginally_ better than downloading, with perhaps the combo `cache_type="all", block_size=8*1024*1024, fill=True` being the best in terms of speed and consistency (although there are perhaps a couple of other choices that would be acceptable as well, as there are a number of choices that performed very similarly to each other).

![image](https://github.com/MAAP-Project/gedi-subsetter/assets/5607545/a1cff650-015d-4537-bf95-f8ae27003dae)

**Comment by wildintellect** [comment]
Based on this can  you just pick one to implement as the default on GEDI Subsetter?

For later, Do we have any sense of the difference in number of requests, or load on the system?

**Comment by chuckwondo** [comment]
Yep, I'm going to set `cache_type="all", block_size=8*1024*1024, fill=True` as the default, but keep `s3fs_open_kwargs` input exposed (and update the docs to explain it).

For later, yes, I need to circle back to find the fsspec PR (I think it's in fsspec) where I believe an option was added to obtain caching metrics.
