### ISSUE TITLE
Change default job queue to maap-dps-worker-32vcpu-64gb

### ISSUE THREAD

**Issue by chuckwondo** [MAAP-Project/gedi-subsetter#78]
Update `algorithm_config.yaml` to use the queue `maap-dps-worker-32vcpu-64gb`. In conjunction, modify `src/gedi_subset/subset.py` to use _all_ available CPUs.

These changes should ensure that by default, the algorithm uses all CPUs on the best available queue for compute to make sure we get the best performance possible.

**Comment by chuckwondo** [comment]
@wildintellect I've made the changes on branch `0.7.1` and I've registered that version of the algo, but I've already merged changes into `main` for reading directly from S3, so I don't want to open a PR to merge the `0.7.1` branch into main since `0.7.1` is still downloading files instead of reading directly from S3.

What's on `main` is still unreleased though. I was waiting to cut a new release from `main` until I finish the experiments on the `s3fs-tuning` branch.

We can still announce the `0.7.1` version though. It will just remain forever unmerged to `main` since `main` now contains logic for direct reads instead of downloads.

**Comment by wildintellect** [comment]
:thinking: but we don't plan on using direct reads over s3 downloads since the files are not cloud optimized. I would think the branch situation would be the reverse. The direct s3 read branch being an orphan experiment, at least until such time that it proves to be better.

**Comment by chuckwondo** [comment]
> 🤔 but we don't plan on using direct reads over s3 downloads since the files are not cloud optimized. I would think the branch situation would be the reverse. The direct s3 read branch being an orphan experiment, at least until such time that it proves to be better.

Perhaps I misunderstood, but I thought our intention was always to drop the downloading approach once we got direct reads working based on the best s3fs cache settings we can manage, as long as performance is comparable to (if not better than) downloading. This is my preference, as long as performance is not significantly worse than downloading, because it would allow us to perform further optimization, if we later find other possible ways to tweak things, even without cloud-optimized files.

**Comment by wildintellect** [comment]
As discussed in the meeting the approach of direct S3 reads instead of Downloads is fine as long as performance is at same or better than the download method.

**Comment by chuckwondo** [comment]
Per findings in #77, we will not be merging the changes on https://github.com/MAAP-Project/gedi-subsetter/tree/0.7.1 into main, but the changes on that branch satisfy this issue, and 0.7.1 was published to MAAP, so it is available.
